CV Ana
MartinMelo97/mujer-digital-g12-git-clone pull request #3
Opened 2024-01-26 08:27 UTC by anaguzman02

cv

2024-01-26 08:56 UTC, anaguzman02 reviewed
Curriculum

2024-01-27 00:26 UTC, MartinMelo97 requested changes

2024-01-27 00:26 UTC, MartinMelo97 commented on ana.guzman.md
> +- **Universidad Autonoma de Chiapas / Educacion Infantil** 2020/2024
```suggestion
- **Universidad Autónoma de Chiapas / Educación Infantil** 2020/2024
```

2024-01-27 00:26 UTC, MartinMelo97 commented on ana.guzman.md
> +- **Ingles / Intermedio**
```suggestion
- **Inglés / Intermedio**
```

2024-01-27 00:26 UTC, MartinMelo97 commented on ana.guzman.md
> +- **Frances / Basico**
```suggestion
- **Francés / Básico**
```

2024-01-27 00:26 UTC, MartinMelo97 commented on ana.guzman.md
> +- **Alfonso Calderon Moreno BUAP / Preparatoria** 2016/2019
```suggestion
- **Alfonso Calderón Moreno BUAP / Preparatoria** 2016/2019
```

2024-01-27 00:49 UTC, MartinMelo97 approved these changes

2024-01-27 00:49 UTC, merged